import nodemailer from "nodemailer";
import { Order } from "./types";

/**
 * Sends an email notification to the store administrator for a new order.
 * If SMTP environment variables are not configured, it will print details to console.
 */
export async function sendOrderNotificationEmail(order: Order) {
  const host = process.env.SMTP_HOST;
  const port = process.env.SMTP_PORT ? parseInt(process.env.SMTP_PORT, 10) : 587;
  const user = process.env.SMTP_USER;
  const pass = process.env.SMTP_PASS;
  const from = process.env.SMTP_FROM || `"Carzo Store" <noreply@carzo.in>`;
  const to = process.env.NOTIFICATION_EMAIL;

  if (!host || !user || !pass || !to) {
    console.log("⚠️ SMTP credentials not fully configured. Skipping order notification email.");
    console.log(`Order CZ ID: ${order.id}`);
    console.log(`Customer: ${order.customer.name} (${order.customer.phone})`);
    console.log(`Total: ${order.total}`);
    return;
  }

  const transporter = nodemailer.createTransport({
    host,
    port,
    secure: port === 465,
    auth: { user, pass },
  });

  const itemsHtml = order.items
    .map(
      (item) => `
    <tr>
      <td style="padding: 8px; border-bottom: 1px solid #ddd;">${item.name}</td>
      <td style="padding: 8px; border-bottom: 1px solid #ddd; text-align: center;">${item.qty}</td>
      <td style="padding: 8px; border-bottom: 1px solid #ddd; text-align: right;">₹${item.price}</td>
      <td style="padding: 8px; border-bottom: 1px solid #ddd; text-align: right;">₹${item.price * item.qty}</td>
    </tr>
  `
    )
    .join("");

  const emailHtml = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; border-radius: 8px;">
      <h2 style="color: #e10600; text-transform: uppercase; font-style: italic; font-family: 'Arial Black', sans-serif;">🏁 New Order Received!</h2>
      <p><strong>Order ID:</strong> ${order.id}</p>
      <p><strong>Date:</strong> ${new Date(order.createdAt).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })} IST</p>
      
      <h3 style="border-bottom: 2px solid #e10600; padding-bottom: 5px; color: #333;">Customer Details</h3>
      <p>
        <strong>Name:</strong> ${order.customer.name}<br>
        <strong>Phone:</strong> ${order.customer.phone}<br>
        <strong>Email:</strong> ${order.customer.email || "N/A"}<br>
        <strong>Shipping Address:</strong><br>
        ${order.customer.address}, ${order.customer.city}, ${order.customer.state} - ${order.customer.pincode}
      </p>

      <h3 style="border-bottom: 2px solid #e10600; padding-bottom: 5px; color: #333;">Items Ordered</h3>
      <table style="width: 100%; border-collapse: collapse; margin-top: 10px;">
        <thead>
          <tr style="background-color: #f8f8f8;">
            <th style="padding: 8px; text-align: left; border-bottom: 2px solid #ddd;">Product</th>
            <th style="padding: 8px; text-align: center; border-bottom: 2px solid #ddd;">Qty</th>
            <th style="padding: 8px; text-align: right; border-bottom: 2px solid #ddd;">Price</th>
            <th style="padding: 8px; text-align: right; border-bottom: 2px solid #ddd;">Subtotal</th>
          </tr>
        </thead>
        <tbody>
          ${itemsHtml}
        </tbody>
        <tfoot>
          <tr>
            <td colspan="3" style="padding: 8px; text-align: right; font-weight: bold;">Total Paid:</td>
            <td style="padding: 8px; text-align: right; font-weight: bold; color: #e10600;">₹${order.total}</td>
          </tr>
        </tfoot>
      </table>

      <p style="margin-top: 20px;">
        <strong>Payment Method:</strong> ${order.paymentMethod === "online" ? "UPI (QR)" : "Cash on Delivery"}<br>
        ${order.paymentId ? `<strong>UPI Reference (UTR):</strong> ${order.paymentId}<br>` : ""}
        <strong>Status:</strong> Pending Confirmation
      </p>

      <div style="margin-top: 30px; text-align: center; font-size: 12px; color: #777; border-top: 1px solid #eee; padding-top: 10px;">
        This email was automatically generated by your Carzo storefront.
      </div>
    </div>
  `;

  await transporter.sendMail({
    from,
    to,
    subject: `🏁 Carzo Order Alert: ${order.id} - ₹${order.total}`,
    html: emailHtml,
  });
}
