import { Product } from "./types";

const now = new Date().toISOString();

export const seedProducts: Product[] = [
  // ---- Diecast / scale models ----
  { id: "p1", slug: "blaze-gt-red", name: "Blaze GT — Crimson Edition", category: "diecast", price: 85, mrp: 120, image: "/products/p1.png", description: "1:64 scale die-cast sports coupe with free-rolling wheels and metallic crimson paint. A must-have starter for every collector.", scale: "1:64", brandLine: "Speed Series", stock: 42, featured: true, createdAt: now },
  { id: "p2", slug: "nitro-hawk-blue", name: "Nitro Hawk — Electric Blue", category: "diecast", price: 95, mrp: 130, image: "/products/p2.svg", description: "1:64 scale muscle car in gloss electric blue with black racing stripes. Die-cast metal body, detailed cabin.", scale: "1:64", brandLine: "Speed Series", stock: 38, createdAt: now },
  { id: "p3", slug: "street-phantom", name: "Street Phantom", category: "diecast", price: 110, mrp: 150, image: "/products/p3.png", description: "Matte-black 1:64 street racer with neon green accents and low-profile wheels.", scale: "1:64", brandLine: "Night Runners", stock: 25, featured: true, createdAt: now },
  { id: "p4", slug: "retro-cruiser-70", name: "Retro Cruiser '70", category: "diecast", price: 99, mrp: 140, image: "/products/p4.svg", description: "Classic 1970s cruiser in sunset orange. 1:64 die-cast with chrome-look bumpers.", scale: "1:64", brandLine: "Classics", stock: 30, createdAt: now },
  { id: "p5", slug: "rally-monster-4x4", name: "Rally Monster 4x4", category: "diecast", price: 149, mrp: 199, image: "/products/p5.svg", description: "1:64 off-road rally truck with oversized wheels and mud-splash livery.", scale: "1:64", brandLine: "Off-Road", stock: 20, createdAt: now },
  { id: "p6", slug: "hyper-v12-silver", name: "Hyper V12 — Silver Storm", category: "diecast", price: 199, mrp: 260, image: "/products/p6.png", description: "Premium 1:43 scale hypercar in brushed silver. Opening detail level for serious collectors.", scale: "1:43", brandLine: "Premium Line", stock: 15, featured: true, createdAt: now },
  { id: "p7", slug: "drift-king-jdm", name: "Drift King JDM", category: "diecast", price: 129, mrp: 170, image: "/products/p7.svg", description: "JDM-style 1:64 drift machine with rear wing and decal pack livery.", scale: "1:64", brandLine: "Night Runners", stock: 33, createdAt: now },
  { id: "p8", slug: "police-interceptor", name: "Police Interceptor", category: "diecast", price: 105, mrp: 145, image: "/products/p8.svg", description: "1:64 highway patrol interceptor with authentic police livery and light-bar detail.", scale: "1:64", brandLine: "City Fleet", stock: 27, createdAt: now },
  { id: "p9", slug: "fire-rescue-truck", name: "Fire Rescue Truck", category: "diecast", price: 159, mrp: 210, image: "/products/p9.svg", description: "1:64 fire rescue unit in classic red with ladder detail. Great for city play sets.", scale: "1:64", brandLine: "City Fleet", stock: 18, createdAt: now },
  { id: "p10", slug: "le-mans-legend-24", name: "Le Mans Legend #24", category: "diecast", price: 249, mrp: 320, image: "/products/p10.svg", description: "1:43 endurance racer with full sponsor livery and race-number decals. Display-case ready.", scale: "1:43", brandLine: "Premium Line", stock: 12, createdAt: now },
  { id: "p11", slug: "mini-hatch-neon", name: "Mini Hatch — Neon Pop", category: "diecast", price: 89, mrp: 125, image: "/products/p11.svg", description: "Cute 1:64 city hatchback in neon pink-purple fade. Pocket-money favourite.", scale: "1:64", brandLine: "Speed Series", stock: 50, createdAt: now },
  { id: "p12", slug: "gold-chrome-limited", name: "Gold Chrome — Limited Run", category: "diecast", price: 499, mrp: 650, image: "/products/p12.svg", description: "Limited-edition 1:43 gold-chrome supercar. Numbered series, collector packaging.", scale: "1:43", brandLine: "Premium Line", stock: 6, featured: true, createdAt: now },
  // ---- RC cars ----
  { id: "p13", slug: "rc-thunder-drift", name: "RC Thunder Drift Pro", category: "rc", price: 1499, mrp: 1999, image: "/products/p13.png", description: "1:18 RC drift car with 2.4GHz remote, drift tyres + grip tyres, 20 km/h top speed, USB rechargeable battery. 40 min run time.", scale: "1:18", brandLine: "RC Pro", stock: 14, featured: true, createdAt: now },
  { id: "p14", slug: "rc-rock-crawler-xt", name: "RC Rock Crawler XT", category: "rc", price: 1899, mrp: 2499, image: "/products/p14.png", description: "4WD RC rock crawler with metal chassis, shock absorbers and all-terrain tyres. Climbs 45° slopes. 2.4GHz, 60 m range.", scale: "1:16", brandLine: "RC Off-Road", stock: 10, createdAt: now },
  { id: "p15", slug: "rc-storm-buggy", name: "RC Storm Buggy 2.4G", category: "rc", price: 1699, mrp: 2199, image: "/products/p15.svg", description: "High-speed RC buggy, 25 km/h, splash-proof body, twin rechargeable batteries included for double play time.", scale: "1:18", brandLine: "RC Off-Road", stock: 12, createdAt: now },
  { id: "p16", slug: "rc-hyper-racer-gt", name: "RC Hyper Racer GT", category: "rc", price: 2499, mrp: 3199, image: "/products/p16.svg", description: "1:14 on-road RC supercar with LED headlights, rubber grip tyres and 30 km/h top speed. Premium alloy detailing.", scale: "1:14", brandLine: "RC Pro", stock: 8, featured: true, createdAt: now },
  { id: "p17", slug: "rc-monster-blaster", name: "RC Monster Blaster 4WD", category: "rc", price: 2999, mrp: 3799, image: "/products/p17.png", description: "Flagship 4WD RC monster truck — 35 km/h, full-proportional steering, metal drive shafts, 100 m range. The beast of the lineup.", scale: "1:12", brandLine: "RC Off-Road", stock: 7, featured: true, createdAt: now },
  { id: "p18", slug: "rc-stunt-tornado", name: "RC Stunt Tornado 360°", category: "rc", price: 1599, mrp: 2099, image: "/products/p18.svg", description: "Double-sided stunt RC car — 360° flips, spins and tumbles. LED wheels, rechargeable, kid-friendly controls.", scale: "1:20", brandLine: "RC Stunt", stock: 16, createdAt: now },
];
